[package]
name = "ts-bindgen-example-paperjs"
version = "0.1.0"
description = "Example of using ts-bindgen to interface with three.js"
authors = ["Adam Berger <adam@ratchetdesigns.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/ratchetdesigns/ts-bindgen"
readme = "README.md"
publish = false

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies]
wasm-bindgen = "0.2.63"
js-sys = "0.3.53"
web-sys = { version = "0.3.53", features = ["Window", "HtmlCanvasElement"] }
ts-bindgen-rt = { version = "0.1.0", path = "../../../ts-bindgen-rt" }
serde = { version = "1.0", features = ["derive"] }
